[build]
  command = "pip install yt-dlp"
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/info"
  to = "/.netlify/functions/info"
  status = 200

[[redirects]]
  from = "/api/download"
  to = "/.netlify/functions/download"
  status = 200

[functions."download"]
  timeout = 120

[functions."info"]
  timeout = 30
